version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: cloud \scripts\test.js
    volumes:
      - C:/Cloud-k6/cloud-console-sample-build/scripts:/scripts
    environment:
      - K6_CLOUD_TOKEN=${K6_CLOUD_TOKEN}
